#!/bin/bash
# scripts/yoyo_context.sh — Build yoyo's identity context for prompts.
# Source this file, then use $YOYO_CONTEXT in any prompt.
#
# Usage:
#   YOYO_REPO="/path/to/yoyo-evolve" source scripts/yoyo_context.sh
#   cat > prompt.txt <<EOF
#   $YOYO_CONTEXT
#   ... your task-specific instructions ...
#   EOF
#
# Reads: IDENTITY.md, PERSONALITY.md, LINEAGE.md, ECONOMICS.md, sponsors/active.json, memory/active_learnings.md, memory/active_social_learnings.md
# These are yoyo's stable identity files — who it is, how it speaks,
# where it sits in the family tree, what it's learned about itself, and what it's learned from humans.

_YOYO_REPO="${YOYO_REPO:-.}"

_IDENTITY=""
if [ -f "$_YOYO_REPO/IDENTITY.md" ]; then
    _IDENTITY=$(cat "$_YOYO_REPO/IDENTITY.md") || {
        echo "WARNING: Failed to read IDENTITY.md" >&2
        _IDENTITY=""
    }
else
    echo "WARNING: IDENTITY.md not found at $_YOYO_REPO/IDENTITY.md" >&2
fi

_PERSONALITY=""
if [ -f "$_YOYO_REPO/PERSONALITY.md" ]; then
    _PERSONALITY=$(cat "$_YOYO_REPO/PERSONALITY.md") || {
        echo "WARNING: Failed to read PERSONALITY.md" >&2
        _PERSONALITY=""
    }
else
    echo "WARNING: PERSONALITY.md not found at $_YOYO_REPO/PERSONALITY.md" >&2
fi

# Lineage — prompt-visible family-tree identity
_LINEAGE=""
if [ -f "$_YOYO_REPO/LINEAGE.md" ]; then
    _LINEAGE=$(cat "$_YOYO_REPO/LINEAGE.md") || _LINEAGE=""
fi

# Active learnings — no warning if missing
_LEARNINGS=""
if [ -f "$_YOYO_REPO/memory/active_learnings.md" ]; then
    _LEARNINGS=$(cat "$_YOYO_REPO/memory/active_learnings.md") || _LEARNINGS=""
fi

# Active social learnings — no warning if missing
_SOCIAL_LEARNINGS=""
if [ -f "$_YOYO_REPO/memory/active_social_learnings.md" ]; then
    _SOCIAL_LEARNINGS=$(cat "$_YOYO_REPO/memory/active_social_learnings.md") || _SOCIAL_LEARNINGS=""
fi

# Active sponsors — generated by evolve.sh each session, persisted in repo
_SPONSORS=""
if [ -f "$_YOYO_REPO/sponsors/active.json" ]; then
    _SPONSORS=$(python3 -c "
import json, sys
try:
    data = json.load(open(sys.argv[1]))
    if data:
        print('Active sponsors:')
        for s in data:
            print(f\"@{s['login']} — {s['amount']} ({s['type']})\")
except Exception as e:
    print(f'WARNING: Failed to parse {sys.argv[1]}: {e}', file=sys.stderr)
" "$_YOYO_REPO/sponsors/active.json") || _SPONSORS=""
fi

# Economics — what money and sponsorship mean to yoyo
_ECONOMICS=""
if [ -f "$_YOYO_REPO/ECONOMICS.md" ]; then
    _ECONOMICS=$(cat "$_YOYO_REPO/ECONOMICS.md") || _ECONOMICS=""
fi

YOYO_CONTEXT="=== WHO YOU ARE ===

${_IDENTITY:-Read IDENTITY.md for your rules and constitution.}

=== YOUR VOICE ===

${_PERSONALITY:-Read PERSONALITY.md for your voice and values.}

=== YOUR LINEAGE ===

${_LINEAGE:-No lineage file found. If you are a repository fork, read LINEAGE.md or your Address Book registration to understand your family-tree generation.}

=== SELF-WISDOM ===

${_LEARNINGS:-No learnings yet.}

=== SOCIAL WISDOM ===

${_SOCIAL_LEARNINGS:-No social learnings yet.}

=== YOUR ECONOMICS ===

${_ECONOMICS:-Read ECONOMICS.md for what money and sponsorship mean to you.}

=== YOUR SPONSORS ===

${_SPONSORS:-No sponsors yet. You are community-supported and free.}"
